### ISSUE TITLE
ROS Nodes Release Date

### ISSUE THREAD

**Issue by Bmoradi93** [chengine/safer-splat#1]
Hello Friends,
Thank you for sharing the code base. I wonder when do you release ROS nodes?

I will be happy to help with that.
Please lemme know.

**Comment by javieryu** [comment]
We're planning on releasing them after the paper is reviewed and the final version is submitted.  I'd imagine that will take at least a few more months.

**Comment by Bmoradi93** [comment]
Perfect!
Looking forward to it.

**Comment by chengine** [comment]
The ROS nodes have now been uploaded to the `ros` branch of this repository.
